name: Run Tests

# Triggers the workflow on push or pull request events
on: [push, pull_request]

jobs:
  test:
    strategy:
      matrix:
        go: [ '1.18', '1.19', '1.20', '1.21', '1.22', '1.23' ]

    runs-on: ubuntu-latest

    name: Go ${{ matrix.go }} Tests
    steps:
      - uses: actions/checkout@v4
 
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go }}
          check-latest: true

      - name: Run all tests
        run: go test -v github.com/knadh/koanf...

      - name: Run Coverage
        run: go test -v -cover ./...
